# Generated by Django 6.0.4 on 2026-04-29 05:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('HOD', 'HOD'), ('BOS', 'BOS'), ('Faculty', 'Faculty')], default='Faculty', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=255)),
                ('courseCode', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('cieMarks', models.IntegerField()),
                ('seeMarks', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending_BOS', 'Pending_BOS'), ('Pending_HOD', 'Pending_HOD'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=50)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('teachingHours', models.IntegerField()),
                ('objectives', models.TextField(blank=True, null=True)),
                ('contentDescription', models.TextField()),
                ('handsOnExercises', models.TextField(blank=True, null=True)),
                ('selfLearningTopics', models.TextField(blank=True, null=True)),
                ('rbtLevels', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='syllabus_api.syllabus')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CoPoMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.CharField(max_length=50)),
                ('po1', models.CharField(blank=True, max_length=10, null=True)),
                ('po2', models.CharField(blank=True, max_length=10, null=True)),
                ('po3', models.CharField(blank=True, max_length=10, null=True)),
                ('po4', models.CharField(blank=True, max_length=10, null=True)),
                ('po5', models.CharField(blank=True, max_length=10, null=True)),
                ('po6', models.CharField(blank=True, max_length=10, null=True)),
                ('po7', models.CharField(blank=True, max_length=10, null=True)),
                ('po8', models.CharField(blank=True, max_length=10, null=True)),
                ('po9', models.CharField(blank=True, max_length=10, null=True)),
                ('po10', models.CharField(blank=True, max_length=10, null=True)),
                ('po11', models.CharField(blank=True, max_length=10, null=True)),
                ('po12', models.CharField(blank=True, max_length=10, null=True)),
                ('pso1', models.CharField(blank=True, max_length=10, null=True)),
                ('pso2', models.CharField(blank=True, max_length=10, null=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coPoMapping', to='syllabus_api.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('userName', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditTrail', to='syllabus_api.syllabus')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
